name: Quality

on:
  push:
  pull_request:

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v21
        with:
          flakehub: false

      - name: Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Check Nix flake
        run: nix flake check ./nix

      - name: Check formatting
        run: nix develop ./nix --command make format-check

      - name: Test project rename
        run: ./scripts/rename-test.sh
