name: Sanitizers

on:
  push:
  pull_request:

jobs:
  sanitizers:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v21
        with:
          flakehub: false

      - name: Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Test with AddressSanitizer and UBSan
        run: nix develop ./nix --command make test-sanitizers
