name: Sanitizers

on:
  push:
    paths:
      - ".github/workflows/sanitizers.yml"
      - "Makefile"
      - "assets/**"
      - "include/**"
      - "meson.build"
      - "meson_options.txt"
      - "nix/**"
      - "scripts/**"
      - "src/**"
      - "tests/**"
      - "vendor/**"
  pull_request:
    paths:
      - ".github/workflows/sanitizers.yml"
      - "Makefile"
      - "assets/**"
      - "include/**"
      - "meson.build"
      - "meson_options.txt"
      - "nix/**"
      - "scripts/**"
      - "src/**"
      - "tests/**"
      - "vendor/**"

jobs:
  sanitizers:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v21
        with:
          flakehub: false

      - name: Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Test with AddressSanitizer and UBSan
        run: nix develop ./nix --command make test-sanitizers
