name: Static analysis

on:
  push:
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v21
        with:
          flakehub: false

      - name: Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Static analysis
        run: nix develop ./nix --command make check
